apiVersion: v1
kind: Service
metadata:
  name: {{ include "horizons-orrery.fullname" . }}
  namespace: horizons
  labels:
    {{- include "horizons-orrery.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "horizons-orrery.selectorLabels" . | nindent 4 }}
